import { defineExtension, ensureValidExtensionManifest } from "@valtren-ai/extension-sdk";

const extension = defineExtension({
  name: "__NAME__",
  version: "0.1.0",
  description: "Node pack scaffold for __LABEL__.",
  agent_catalog: {
    workflows: [
      {
        key: "__NAME___workflow",
        label: "__LABEL__ Workflow",
        description: "Describe the governed workflow this extension should contribute.",
        steps: ["analyze_evidence"]
      }
    ],
    templates: [
      {
        key: "__NAME___starter",
        label: "__LABEL__ Starter",
        description: "Starter template generated by create-valtren-extension.",
        workflow: "__NAME___workflow"
      }
    ]
  }
});

ensureValidExtensionManifest(extension);
export default extension;
